# Generated by Django 4.2 on 2024-05-15 06:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AccessCard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "card_number",
                    models.CharField(max_length=50, verbose_name="card number"),
                ),
                (
                    "is_allocated",
                    models.BooleanField(default=False, verbose_name="is allocated"),
                ),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, verbose_name="created"),
                ),
                (
                    "updated",
                    models.DateTimeField(auto_now=True, verbose_name="updated"),
                ),
                (
                    "address",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="user.address",
                        verbose_name="address id",
                    ),
                ),
            ],
            options={
                "verbose_name": "accesscard",
                "verbose_name_plural": "accesscards",
            },
        ),
        migrations.CreateModel(
            name="Approval",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, verbose_name="created"),
                ),
                (
                    "updated",
                    models.DateTimeField(auto_now=True, verbose_name="updated"),
                ),
                (
                    "access_card",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="approval_access_card",
                        to="visitor.accesscard",
                        verbose_name="access card id",
                    ),
                ),
            ],
            options={
                "verbose_name": "approval",
                "verbose_name_plural": "approvals",
            },
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="name")),
            ],
            options={
                "verbose_name": "category",
                "verbose_name_plural": "categories",
            },
        ),
        migrations.CreateModel(
            name="Host",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="name")),
                ("email", models.EmailField(max_length=254, verbose_name="email")),
                ("phone", models.BigIntegerField(verbose_name="phone number")),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, verbose_name="created"),
                ),
                (
                    "updated",
                    models.DateTimeField(auto_now=True, verbose_name="updated"),
                ),
            ],
            options={
                "verbose_name": "host",
                "verbose_name_plural": "hosts",
            },
        ),
        migrations.CreateModel(
            name="NIDType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="name")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="is_active"),
                ),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, verbose_name="created"),
                ),
                (
                    "updated",
                    models.DateTimeField(auto_now=True, verbose_name="updated"),
                ),
            ],
            options={
                "verbose_name": "nid-type",
                "verbose_name_plural": "nid-types",
            },
        ),
        migrations.CreateModel(
            name="VisitorDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="name"
                    ),
                ),
                ("email", models.EmailField(max_length=254, verbose_name="email")),
                (
                    "phone",
                    models.BigIntegerField(
                        blank=True, null=True, verbose_name="phone number"
                    ),
                ),
                (
                    "photo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="visitor_photos",
                        verbose_name="photo",
                    ),
                ),
                (
                    "signature",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="signatures",
                        verbose_name="signature",
                    ),
                ),
                (
                    "company",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="company"
                    ),
                ),
                (
                    "national_id",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="national_ids",
                        verbose_name="national id",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, verbose_name="created"),
                ),
                (
                    "updated",
                    models.DateTimeField(auto_now=True, verbose_name="updated"),
                ),
                (
                    "nid_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nid_type",
                        to="visitor.nidtype",
                        verbose_name="national identity type",
                    ),
                ),
            ],
            options={
                "verbose_name": "visitor-detail",
                "verbose_name_plural": "visitor-details",
            },
        ),
        migrations.CreateModel(
            name="Valid",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "otp",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="otp"
                    ),
                ),
                (
                    "is_valid",
                    models.BooleanField(
                        blank=True, default=False, null=True, verbose_name="is_valid"
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, verbose_name="created"),
                ),
                (
                    "updated",
                    models.DateTimeField(auto_now=True, verbose_name="updated"),
                ),
                (
                    "visitor",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="valid",
                        to="visitor.visitordetail",
                        verbose_name="visitor_id",
                    ),
                ),
            ],
            options={
                "verbose_name": "valid",
                "verbose_name_plural": "valids",
            },
        ),
        migrations.CreateModel(
            name="Timing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("check_in", models.DateTimeField(verbose_name="check in")),
                (
                    "check_out",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="check out"
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, verbose_name="created"),
                ),
                (
                    "updated",
                    models.DateTimeField(auto_now=True, verbose_name="updated"),
                ),
                (
                    "approval",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="timing",
                        to="visitor.approval",
                        verbose_name="approval id",
                    ),
                ),
            ],
            options={
                "verbose_name": "timing",
                "verbose_name_plural": "timings",
            },
        ),
        migrations.CreateModel(
            name="PurposeOfVisit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="name")),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="visitor.category",
                        verbose_name="category_id",
                    ),
                ),
            ],
            options={
                "verbose_name": "purpose of visit",
                "verbose_name_plural": "purpose of visits",
            },
        ),
        migrations.AddField(
            model_name="approval",
            name="host",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="approval_host",
                to="visitor.host",
                verbose_name="host id",
            ),
        ),
        migrations.AddField(
            model_name="approval",
            name="purpose_of_visit",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="visitor.purposeofvisit",
                verbose_name="purpose_of_visit id",
            ),
        ),
        migrations.AddField(
            model_name="approval",
            name="visitor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="approval",
                to="visitor.visitordetail",
                verbose_name="visitor id",
            ),
        ),
        migrations.AddField(
            model_name="accesscard",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="visitor.category",
                verbose_name="category_id",
            ),
        ),
    ]
