# Generated by Django 4.2 on 2024-02-21 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visitor', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='visitordetail',
            options={'verbose_name': 'visitor-detail', 'verbose_name_plural': 'visitor-details'},
        ),
    ]
